# Use root/example as user/password credentials
version: '3.1'

services:

  mariadb:
    image: mariadb:latest
    environment:
      MARIADB_ROOT_PASSWORD: wachtwoord
      MARIADB_DATABASE: milestone
    ports:
      - 1234:3306

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mariadb

  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 8000:8000
    depends_on:
      - mariadb

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8085:80
    depends_on:
      - fastapi