apiVersion: v1
kind: Service
metadata:
  labels:
    milestone-app: adminer
  name: adminer
spec:
  type: LoadBalancer
  ports:
    - name: "8080"
      port: 8080
      targetPort: 8080
  selector:
    milestone-app: adminer