apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  labels:
    milestone-app: adminer
spec:
  replicas: 1
  selector:
    matchLabels:
      milestone-app: adminer
  template:
    metadata:
      labels:
        milestone-app: adminer
    spec:
      containers:
        - name: adminer
          image: adminer
          ports:
            - containerPort: 8080