apiVersion: v1
kind: Service
metadata:
  labels:
    milestone-app: mariadb
  name: mariadb
spec:
  type: ClusterIP
  selector:
    milestone-app: mariadb
  ports:
    - name: "3306"
      port: 3306
      targetPort: 3306