apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    milestone-app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      milestone-app: nginx
  template:
    metadata:
      labels:
        milestone-app: nginx
    spec:
      containers:
        - name: nginx
          image: jonasbaelus/nginx
          ports:
            - containerPort: 80