apiVersion: v1
kind: Service
metadata:
  labels:
    milestone-app: nginx
  name: nginx
spec:
  type: LoadBalancer
  ports:
    - name: "8085"
      port: 8085
      targetPort: 80
  selector:
    milestone-app: nginx